[package]
name = "blackjack-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rustfmt = "0.10.0"
tokio = {version="1.22.0", features=["full"]}

